### ISSUE TITLE
install multiple packages

### ISSUE THREAD

**Issue by martinerk0** [RoboStack/robostack.github.io#10]
Is there a way to install multiple packages at once? For example rqt is split into many separate packages, I would like to install them all with like **mamba install ros-noetic-rqt-*** ?

**Comment by Tobias-Fischer** [comment]
This works somewhat but not fully as it should: `mamba install 'ros-noetic-rqt*'`

/cc @wolfv

**Comment by wolfv** [comment]
Quoting is sometimes necessary depending on the shell that is used

**Comment by Tobias-Fischer** [comment]
But it's broken in the sense that 'ros-noetic-*' doesn't install all available packages for some reason

**Comment by wolfv** [comment]
I opened an issue on the mamba repository :)
