### ISSUE TITLE
ros-noetic-pid on osx-64 fails to install

### ISSUE THREAD

**Issue by valschmidt** [RoboStack/robostack.github.io#13]
New Robostack user here, so maybe missing something simple. 
The following, executed on :

`mamba install -c robostack -c robostack-experimental -c conda-forge ros-noetic-pid`

results in

```
Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - package ros-noetic-pid-0.0.28-py38hb43b470_11 requires python, but none of the providers can be installed
```

I have a similar error to an installation of `ros-noetic-sound-play`.

**Comment by Tobias-Fischer** [comment]
See e.g. https://github.com/RoboStack/ros-noetic/pull/271 on how to add packages. Please open a pull request :)

**Comment by Tobias-Fischer** [comment]
Just a little more explanation: these packages basically haven't been built yet (we only build a limited set of packages, including desktop-full, the navigation stack, moveit and a few others). But adding new packages is easy as you can see from the pull request above - it's simply adding a new line per package. The packages are then built in our CI and uploaded for everyone to use.

**Comment by Tobias-Fischer** [comment]
Fixed: https://github.com/RoboStack/ros-noetic/pull/336
