### ISSUE TITLE
Installation step not working as mentioned in the GitHub pages but step are working fine as mention in readme file  

### ISSUE THREAD

**Issue by VikasPoddar** [RoboStack/robostack.github.io#14]
system information 
OS : Pop!_OS 22.04
Host : Vmware Virtual Platform
kernel : 5.19.0
Details :
I was trying out way to install ROS, I tried by tradition install in wsl Ubuntu, then I tried to do same but with RoboStack in PopOS by following the gitpage guide (link : https://robostack.github.io/GettingStarted.html)
## incorrect install
steps prefromed :
conda install mamba -c conda-forge

mamba create -n ros_env python=3.9
conda activate ros_env

conda config --env --add channels conda-forge

conda config --env --add channels robostack
conda config --env --add channels robostack-experimental

mamba install ros-galactic-desktop   [AT THIS COMMAND THE FAILURE OCCOURED]

it caused multi-install failure,
due to error 404 in robostack-exprimental

## correct install
but later on I followed the github readme doc (link : https://github.com/RoboStack/ros-noetic ) and medium article (link : https://medium.com/robostack/cross-platform-conda-packages-for-ros-fa1974fd1de3) 

steps followed :  

conda install mamba -c conda-forge

mamba create -n robostackenv ros-noetic-desktop python=3.9 -c robostack -c robostack-experimental -c conda-forge --no-channel-priority --override-channels
conda activate robostackenv
mamba install compilers cmake pkg-config make ninja
mamba install catkin_tools
conda deactivate
conda activate robostackenv
mamba install rosdep
rosdep init  
rosdep update

everything run great !!! for these set of command .

please consider this issue

**Comment by Tobias-Fischer** [comment]
This should be fixed with the latest instructions. Many thanks for reporting this!

**Comment by VikasPoddar** [comment]
@Tobias-Fischer Thank you for the help
