### ISSUE TITLE
Fix table layout

### ISSUE THREAD

**Issue by Tobias-Fischer** [RoboStack/robostack.github.io#2]
For some reason and not all the time, some of the columns get truncated. I already tried setting the width manually and explicitly setting the maximum width to None, but still it doesn't work. On my local machine things are working fine. Any idea @wolfv?

**Comment by wolfv** [comment]
no idea... maybe a missing closeing / flushing of the file?

**Comment by Tobias-Fischer** [comment]
Seems like your constant width fix works, thanks :).

**Comment by wolfv** [comment]
I hope I fixed that by setting a fixed width.

**Comment by wolfv** [comment]
ah, just saw that you already closed :)
