### ISSUE TITLE
Channel seems to be broken

### ISSUE THREAD

**Issue by zspasztori** [RoboStack/robostack.github.io#20]
Can't install ros packages anymore on Ubuntu 22 from robostack-staging in python 3.9 environment.

Looking for: ['ros-noetic-desktop-full']

robostack-staging/noarch                           130.0 B @ 238.0 B/s  0.5s
robostack-staging/linux-64                         237.6kB @ 151.7kB/s  1.6s
conda-forge/noarch                                  11.5MB @   3.9MB/s  3.1s
conda-forge/linux-64                                30.1MB @   2.9MB/s 10.7s

Pinned packages:
  - python 3.9.*

Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested ros-noetic-desktop-full

The environment can't be solved, aborting the operation

**Comment by Tobias-Fischer** [comment]
Hi there,

I can't replicate this issue. Could you please provide the full set of commands that you run? The command listed in the https://github.com/RoboStack/ros-noetic README works for me.

Feel free to reopen :).

**Comment by traversaro** [comment]
We also had a similar (temporary) problem with the `robotology` channel, see https://github.com/robotology/human-dynamics-estimation/pull/341#discussion_r1129760058 . I think there was a temporary outage on the channel hosted on anaconda, but that did non affected channels distributed over a CDN such as `conda-forge` or `bioconda`, so most users did not realized this.
