### ISSUE TITLE
PyEnv related recommendations... installing/managing Conda for RoboStack

### ISSUE THREAD

**Issue by techdragon** [RoboStack/robostack.github.io#28]
This isn't about somehow using RoboStack without Conda or criticising the use of Conda, since obviously it works fine for some people... but for me...

The thought of just blindly installing anything Conda related (conda/conda-forge/mamba/etc) is genuinely a psychologically uncomfortable one for me, I've been burned too badly trying them, I can only jam my hand in the toaster so many times, the hair pulling frustration, the hours and days lost to fixing and cleaning up multiple computers from Conda related issues sometimes just from installing it, the lost time unable to work because it broke the machine I use to do paid work needing functioning python environments... but since RoboStack seems to be the only working and tested way to get ROS2 installed on an M1 Mac (without disabling SIP), and RoboStack uses/requires Conda, I need to find a way to use the Conda ecosystem that won't make me regret it yet another time. 

Since PyEnv can theoretically install and manage Conda has anyone installed Conda using Pyenv and used that to run RoboStack?

**Comment by Tobias-Fischer** [comment]
Hi @techdragon,
Thanks for reaching out.
You can use micromamba, which is just a self-contained executable: https://mamba.readthedocs.io/en/latest/micromamba-installation.html. If you don't like it, you can simply delete it, and delete the environment folder, and your system is just like before.
The pyenv question seems more related to conda/conda-forge in general (or even pyenv itself), so your question is probably better placed there.

Best, Tobi

**Comment by techdragon** [comment]
Thanks for the reply @Tobias-Fischer 

`micromamba` not shipping with its own Python is a promising option, so its good to know that RoboStack works with `micromamba`. I'll have to look into it more and see if it works ok.
