### ISSUE TITLE
rostopic echo /turtle1/pose ERROR: Cannot load message class for [turtlesim/Pose]. Are your messages built?

### ISSUE THREAD

**Issue by jmstadt** [RoboStack/robostack.github.io#34]
Hello, I am new to ROS and I successfully loaded robostack onto my Mac.   I am working through this tutorial.  https://www.youtube.com/playlist?list=PLLSegLrePWgIbIrA4iehUQ-impvIXdd9Q.  Everything works fine until I get to tutorial six and when I try to enter on the command line:

`rostopic echo /turtle1/pose`

I get the following error:

`ERROR: Cannot load message class for [turtlesim/Pose]. Are your messages built?`

turtlesim works fine for everything else, so I continued through toward tutorial 8.  But, that requires:

`from turtlesim.msg import Pose`

And the import shows no turtlesim let alone turtlesim.msg.

I have rerun catkin_make and I have also made sure that all the terminals have sourced the devel/setup.bash.  I have not edited anything on CMakeLists.txt although the commented fields do talk about building messages.  However, not sure if that is required and if so, how to do that.  The tutorial does not do that at all and on their youtube seems to work fine. (although they seem to be using ROS Noetic directly on Ubuntu.

**Comment by Tobias-Fischer** [comment]
Hi,
Can you please open another issue at https://github.com/RoboStack/ros-noetic/issues and provide the requested information? Also, have you tried a simple `mamba install ros-noetic-turtlesim`?

Many thanks!

**Comment by jmstadt** [comment]
Will do.  Thank you!  When I enter on the command line:

`rostopic echo /turtle1/cmd_lel`

It works fine. I.e.:

```
---
linear: 
  x: 1.0
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0
---
```
`But, when I enter rostopic echo /turtle1/pose`

I get the:

`ERROR: Cannot load message class for [turtlesim/Pose]. Are your messages built?
`
So thinking that turtlesim is installed, but will try installing or uninstalling and then installing and then report on that in the link you provided.  Thank you!
