### ISSUE TITLE
time efficiency

### ISSUE THREAD

**Issue by TE-HA** [RoboStack/robostack.github.io#38]
Thanks for your wonderful work! I wonder that whether this way install all packages in Conda will cost more time than general way or not?

**Comment by Tobias-Fischer** [comment]
Hi @TE-HA, it’s great to hear you like RoboStack! The binaries run bare metal without any virtualisation, so in theory there is no overhead.

That said, some optimisations are not enabled to ensure compatibility with older hardware, so there might be some cases where it will run slightly slower compared to e.g. Arch Linux where you compile stuff yourself with full optimisation for your system.

In practice, RoboStack binaries should run as fast as the Ubuntu ones provided by ROS upstream.

I hope this helps :)
