### ISSUE TITLE
Package ros-noetic-controller-manager-msgs is unavailable

### ISSUE THREAD

**Issue by AleksandrKashirin** [RoboStack/robostack.github.io#41]
Hi, I have installed **robostack** through _micromamba_ and for my project it is required to use` ros-noetic-controller-manager-msgs`. However, the required package is missing in my ros environment. I did not find any instructions on how should I fix this, except cloning source file from git for the required package.

Thank you!
- Aleksandr

**Comment by Tobias-Fischer** [comment]
Indeed, this package is available on all platforms - see https://anaconda.org/robostack-staging/ros-noetic-controller-manager-msgs.

Feel free to reopen to clarify things further.
