### ISSUE TITLE
ros-humble-marker-msgs package request

### ISSUE THREAD

**Issue by jfrancis71** [RoboStack/robostack.github.io#44]
Could I place a request for the ros-humble-marker-msgs package to be added? (I'm on a Linux Intel platform)

I'd like to be able to visualise some 3D objects that I have in my environment in rviz2.

I understand the interactive markers have been done, but I don't really want to use these as my markers correspond to physical objects, and I don't want users to try and click on markers to move them.

I understand the package is quite widely used, so this might be of general interest? I would try myself, but I think this might be a bit beyond me at this stage.

Thanks.

**Comment by Tobias-Fischer** [comment]
Fixed in https://github.com/RoboStack/ros-humble/pull/156
