### ISSUE TITLE
A tutorial for packaging a private ROS2 package? 

### ISSUE THREAD

**Issue by MaximilianHoffmann** [RoboStack/robostack.github.io#46]
Thanks for developing this packaged version of ROS. I'd really like to use it on all my machines to fully streamline the installation of a given ros2 + custom packages. For this I'd like to package my private custom ROS2 packages and currently don't really know how this would work. Is there maybe a tutorial or something I didn't see?

**Comment by traversaro** [comment]
I guess that the "Adding new packages to RoboStack" in the RoboStack paper covers that case https://arxiv.org/pdf/2104.12910 . It requires to have the package.xml for the packages you want to package, and use [vinca](https://github.com/RoboStack/vinca) and [boa](https://github.com/mamba-org/boa). I am not super sure everything works at the moment, but I guess the best thing to proceed is that you try to package a custom package of yours, and open an issue if something is not working, thanks!
