### ISSUE TITLE
Error when importing cv_bridge

### ISSUE THREAD

**Issue by Lancial** [RoboStack/robostack.github.io#47]
Hi, great work for creating this software!

I'm getting an error when trying to import cv_bridge. The error message was

```
>>> import cv_bridge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/envs/ros-torch/lib/python3.9/site-packages/cv_bridge/__init__.py", line 6, in <module>
    from cv_bridge.boost.cv_bridge_boost import cvtColorForDisplay, getCvType
TypeError: 'Boost.Python.function' object has no attributes (assign to .__doc__)
```

System: ubuntu 20.04, python: 3.9, ROS1, in a docker environment with mamba.

Does anyone know how to resolve this issue? Thank you!

**Comment by Tobias-Fischer** [comment]
It seems like you’re using old Python 3.9 builds - please follow our instructions to use our recent Python 3.11 builds. If the problem still persists, please open an issue in our ros-Noetic repository and provide all the requested information.

Many thanks!
