### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by richardrl** [RoboStack/robostack.github.io#49]
Is there any documentation on how to do basic things with Robostack?

Seems many things from standard ros do not transfer exactly, like where packages are stored

**Comment by richardrl** [comment]
Another example: how to launch RViz2 with a specific URDF?

**Comment by traversaro** [comment]
> Seems many things from standard ros do not transfer exactly, like where packages are stored

Can you be more specific? I am not sure how that is different, beside the difference of apt vs conda. Do you have an example of ROS official docs that should be changed for robostack?

**Comment by traversaro** [comment]
> Another example: how to launch RViz2 with a specific URDF?

In which sense this is different in robostack?

**Comment by richardrl** [comment]
Where are packages installed? I am trying to follow this: https://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch

And cannot get any `ros2 launch urdf_tutorial` to work in robostack

**Comment by richardrl** [comment]
I want to load the rviz with my urdf

**Comment by richardrl** [comment]
Could you provide a line by line explanation of how to load the URDF into Rviz with Robostack?

**Comment by traversaro** [comment]
That documentation is for ROS 1, you are using ROS 2. The correct docs to check are https://docs.ros.org/en/humble/Tutorials/Intermediate/URDF/Building-a-Visual-Robot-Model-with-URDF-from-Scratch.html . The location where the `urdf-tutorial` files are installed is `$CONDA_PREFIX\share\urdf_tutorial`, but you do not need to know that if you execute the command later in the tutorial. However, that seems to me a lack of the tutorial in https://docs.ros.org/en/humble/Tutorials/Intermediate/URDF/Building-a-Visual-Robot-Model-with-URDF-from-Scratch.html, as it should not assume that the user has the pwd in some binary directory, or it should explain the user how to reach it.

**Comment by richardrl** [comment]
> That documentation is for ROS 1, you are using ROS 2. The correct docs to check are https://docs.ros.org/en/humble/Tutorials/Intermediate/URDF/Building-a-Visual-Robot-Model-with-URDF-from-Scratch.html . The location where the `urdf-tutorial` files are installed is `$CONDA_PREFIX\share\urdf_tutorial`, but you do not need to know that if you execute the command later in the tutorial. However, that seems to me a lack of the tutorial in https://docs.ros.org/en/humble/Tutorials/Intermediate/URDF/Building-a-Visual-Robot-Model-with-URDF-from-Scratch.html, as it should not assume that the user has the pwd in some binary directory, or it should explain the user how to reach it.

Thanks for your response.

these were the steps I tried, without success and error at the end:
micromamba install ros-humble-urdf-tutorial -c conda-forge -c robostack-staging ros-humble-desktop 
and after installation,
ros2 launch urdf_tutorial display.launch model:=urdf/01-myfirst.urdf file 'display.launch' was not found in the share directory of package 'urdf_tutorial' which is at '/samsung4tb/conda_envs/ros_env/share/urdf_tutorial'



Any idea whats happening?

**Comment by richardrl** [comment]
I got it to work with this command: ros2 launch urdf_tutorial display.launch.py model:=urdf/01-myfirst.urdf

seems you need to append a .py to any launch files

**Comment by richardrl** [comment]
An additional step:
I searched for package:// in my urdf and changed all the meshes to the directory that robostack is expecting. Now I can load my custom URDF and associated meshes

**Comment by traversaro** [comment]
> I got it to work with this command: ros2 launch urdf_tutorial display.launch.py model:=urdf/01-myfirst.urdf
> 
> seems you need to append a .py to any launch files

In which sense "add" ? That seems the command reported in https://docs.ros.org/en/humble/Tutorials/Intermediate/URDF/Building-a-Visual-Robot-Model-with-URDF-from-Scratch.html .
