### ISSUE TITLE
Jazzy packages table show 404

### ISSUE THREAD

**Issue by azazdeaz** [RoboStack/robostack.github.io#52]
https://github.com/RoboStack/ros-jazzy points to https://robostack.github.io/jazzy.html which it shows 404 atm.

But seems like the packages are already there: https://anaconda.org/search?q=jazzy (Which is awesome! :tada: Thank you so much!! :heart: )

Or is Jazzy not officially supported yet?

**Comment by Tobias-Fischer** [comment]
We’re still working on it .. as far as I know, no one has properly tested any of the packages

**Comment by azazdeaz** [comment]
Ah i see, thank you for the answer!!
