### ISSUE TITLE
Package in conda-forge some dependencies used by ROS 2 Rolling as of October 2024

### ISSUE THREAD

**Issue by traversaro** [RoboStack/robostack.github.io#56]
Useful packages:
* [ ] `uncrustify` : https://github.com/uncrustify/uncrustify (not pure python, so we should pay attention)
* [x] `flake8-deprecated` : pure python, easy: https://github.com/conda-forge/staged-recipes/pull/27860
* [ ] colcon-ros-domain-id-coordinator
* [ ] fastjsonschema 
* [ ] `flake8-class-newline`

fyi @clalancette

**Comment by Tobias-Fischer** [comment]
Note that all are now available:
- https://prefix.dev/channels/conda-forge/packages/python-fastjsonschema
- https://prefix.dev/channels/conda-forge/packages/uncrustify
- https://prefix.dev/channels/conda-forge/packages/flake8-class-newline
- https://prefix.dev/channels/conda-forge/packages/colcon-ros-domain-id-coordinator

Should we close here or is there more to be done @traversaro?

**Comment by traversaro** [comment]
Sure, thanks!
