### ISSUE TITLE
Should the installation tutorial for ros1 target a lower version (or a proper) of Python?

### ISSUE THREAD

**Issue by FireWolves** [RoboStack/robostack.github.io#57]
The Python version for ROS1 in the tutorial is `3.11`, it seems that some ROS packages depend on `Boost 1.78`, but the highest version of Python that `Boost 1.78` depends on is `Python 3.10`. I switched it to `Python 3.10` but still encountered some issues; `Python 3.9` works very well.

**Comment by vskarleas** [comment]
Python 3.11 but for some Ubuntu distributions that are earlier than 22.3 python 3.9 will work without any issues. On the other hand 3.11 may provoke minor issues depending on the system’s parameters.

**Comment by Tobias-Fischer** [comment]
RoboStack builds on top of conda, which ships its own python (as well as boost etc.). Therefore, we can support newer python/boost than what seems to be supported by some ROS packages. If you have specific issues, please open an issue following the template at https://github.com/RoboStack/ros-noetic
